name: Hello World CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World!"

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
       java-version: '18'
       distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build

      
    - name: Display Secret 
      run: |
        echo  $MY_SECRET
      env: 
        MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: Run Script
      run: bash ./run.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Dockerhub 
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: leonaistrefi/app:latest

   
        
