name: Hello World CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World!"
      
    - name: Display Secret 
      run: |
        echo  $MY_SECRET
      env: 
        MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: Run Script
      run: bash ./run.sh

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.JUMP_HOST }}
        username: ${{ secrets.JUMP_USERNAME }}
        password: ${{ secrets.JUMP_PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD}}
        script: echo "Hello World"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Dockerhub 
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: leonaistrefi/app:latest

   
        
