name: Hello World CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World!"

     # Set up JDK 18
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
          java-version: '18'
          distribution: 'adopt'

      # Make gradlew executable (use the correct path to gradlew)
    - name: Make gradlew executable
      run: chmod +x ./uek223_team3_Leo_Ram_Backend/gradlew

      # Build the project using Gradle (use the correct path)
    - name: Build with Gradle
      run: ./uek223_team3_Leo_Ram_Backend/gradlew build

      # Test the project using Gradle (use the correct path)
    - name: Test with Gradle
      run: ./uek223_team3_Leo_Ram_Backend/gradlew test
      
    - name: Display Secret 
      run: |
        echo  $MY_SECRET
      env: 
        MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: Run Script
      run: bash ./run.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Dockerhub 
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: leonaistrefi/app:latest

   
        
